# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e2c57b5b7bd6ae4e3e576e0d50cda3692fa055a37d23f4849311fcda3ce5d5bb94f1cf3d0eb0294047a55ed8fcecfaee0df790ca5cd5b567c7b2f89c0bdd3a

test:
  secret_key_base: c183f7c03b49449ad2034e40129738c86cf5d0d826ba9ae3b813ca360fcca03f7178e4334e1f4a217785806b062b43d7e9807ac62a7e843bb0f0e3fe8a009fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
